name: test
on: push
jobs:
  test:
    runs-on: ubuntu-22.04
    container: ryuichiueda/ubuntu22.04-ros2:latest
    steps:
      - uses: actions/checkout@v2
      - name: build and test
        run: |
          rsync -av ./ /root/ros2_ws/src/mypkg/
          cd /root/ros2_ws
          source /opt/ros/humble/setup.bash
      - name: build and test
        run: |
          cd /root/ros2_ws
          colcon build --packages-select mypkg
          source install/setup.bash
          bash -xv ./src/mypkg/test/test.bash /root
