name: test
on: push
jobs:
  test:
    runs-on: ubuntu-22.04
    container: ryuichiueda/ubuntu22.04-ros2:latest
    steps:
      - uses: actions/checkout@v2
      - name: debug workspace setup
        run: |
          echo "Starting Workspace Setup"
          mkdir -p /root/ros2_ws/src
          rsync -av ./ /root/ros2_ws/src/mypkg/
          ls -la /root/ros2_ws/src/mypkg
      - name: setup ros 2 environment
        shell: bash
        run: |
          echo "Sourcing ROS 2 Envitonment"
          export ROS_DISTRO=foxy
          source /opt/ros/humble/setup.bash
          colcon list
      - name: build package
        shell: bash
        run: |
          cd /root/ros2_ws
          source /opt/humble/setup.bash
          colcon build --packages-select mypkg
          ls -la install
      - name: run test script
        shell: bash
        run: |
          cd /root/ros2_ws
          source /opt/humble/setup.bash
          bash -xv ./src/mypkg/test/test.bash /root
